-- Run once in the Supabase SQL Editor before deploying PayPal Checkout.
alter table public.orders add column if not exists payment_provider text, add column if not exists checkout_session_hash text, add column if not exists paypal_order_id text, add column if not exists paypal_capture_id text, add column if not exists paid_amount numeric(12,2), add column if not exists paid_currency text, add column if not exists paid_at timestamptz, add column if not exists receipt_email_sent_at timestamptz;
create index if not exists orders_checkout_session_hash_index on public.orders (checkout_session_hash) where checkout_session_hash is not null;
create unique index if not exists orders_paypal_order_id_unique on public.orders (paypal_order_id) where paypal_order_id is not null;
create unique index if not exists orders_paypal_capture_id_unique on public.orders (paypal_capture_id) where paypal_capture_id is not null;
create table if not exists public.payment_webhook_events (id bigint generated by default as identity primary key, provider text not null, event_id text not null, event_type text, payload jsonb not null, created_at timestamptz not null default now(), unique(provider,event_id));
create or replace function public.finalize_paypal_payment(p_order_id bigint,p_paypal_order_id text,p_paypal_capture_id text,p_paid_amount numeric,p_paid_currency text,p_payer_email text,p_paid_at timestamptz) returns jsonb language plpgsql security definer set search_path=public as $$
declare current_order public.orders%rowtype;
begin
 select * into current_order from public.orders where id=p_order_id for update;
 if not found then raise exception 'Order not found'; end if;
 if current_order.payment_provider is distinct from 'paypal' or current_order.paypal_order_id is distinct from p_paypal_order_id then raise exception 'Payment reference mismatch'; end if;
 if current_order.payment_status='Paid' then if current_order.paypal_capture_id=p_paypal_capture_id then return jsonb_build_object('already_paid',true); end if; raise exception 'Order already paid'; end if;
 if current_order.total_price::numeric(12,2)<>p_paid_amount::numeric(12,2) or p_paid_currency<>'USD' then raise exception 'Payment amount mismatch'; end if;
 if exists(select 1 from public.orders where paypal_capture_id=p_paypal_capture_id and id<>p_order_id) then raise exception 'Capture already used'; end if;
 update public.orders set payment_status='Paid',status='Pending',paypal_capture_id=p_paypal_capture_id,paid_amount=p_paid_amount,paid_currency=p_paid_currency,paid_at=coalesce(p_paid_at,now()),payer_email=coalesce(p_payer_email,payer_email) where id=p_order_id;
 return jsonb_build_object('finalized',true);
end; $$;
revoke all on function public.finalize_paypal_payment(bigint,text,text,numeric,text,text,timestamptz) from public;
grant execute on function public.finalize_paypal_payment(bigint,text,text,numeric,text,text,timestamptz) to service_role;