"use client";
import { useEffect, useRef, useState } from "react";

declare global { interface Window { paypal?: any } }
type Props={ disabled:boolean; details:{robloxUsername:string;robloxUserId:number|null;contactInfo:string;notes:string;items:{id:number;quantity:number}[];couponCode?:string}; };
export default function PaypalCheckout({disabled,details}:Props){
 const paypalRef=useRef<HTMLDivElement>(null),cardRef=useRef<HTMLDivElement>(null),detailsRef=useRef(details); detailsRef.current=details; const [message,setMessage]=useState(""),[ready,setReady]=useState(false);
 useEffect(()=>{const clientId=process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID;if(!clientId){setMessage("PayPal sandbox is not configured yet.");return;}let dead=false;
 const render=()=>{if(dead||!window.paypal)return;if(paypalRef.current) paypalRef.current.replaceChildren();if(cardRef.current) cardRef.current.replaceChildren();const make=(source:any,el:React.RefObject<HTMLDivElement|null>)=>{const button=window.paypal.Buttons({fundingSource:source,style:{layout:"vertical",shape:"rect",label:"paypal",tagline:true},createOrder:async()=>{setMessage("Creating secure payment...");const r=await fetch("/api/paypal/create-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(detailsRef.current)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Creating secure payment failed.");setMessage("");return d.orderID;},onApprove:async(data:any)=>{setMessage("Payment processing...");const r=await fetch("/api/paypal/capture-order",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderID:data.orderID})});const d=await r.json();if(!r.ok){setMessage(d.error||"Payment could not be completed. Please try again.");return;}setMessage("Payment completed successfully.");window.location.assign("/payment-success?orderId="+encodeURIComponent(d.bloxhopOrderId));},onCancel:()=>setMessage("Payment was cancelled. You can try again."),onError:()=>setMessage("Payment could not be completed. Please try again.")});if(button.isEligible()&&el.current)button.render(el.current);};make(window.paypal.FUNDING.PAYPAL,paypalRef);make(window.paypal.FUNDING.CARD,cardRef);setReady(true);};
 if(window.paypal){render();return()=>{dead=true;};}const script=document.createElement("script");script.src="https://www.paypal.com/sdk/js?client-id="+encodeURIComponent(clientId)+"&currency=USD&intent=capture&components=buttons,funding-eligibility";script.async=true;script.onload=render;document.body.appendChild(script);return()=>{dead=true;};},[]);
 return <div className="mt-5 rounded-lg border border-white/10 bg-[#1d1c31] p-4"><h3 className="text-base font-black text-white">Payment Method</h3><p className="mt-1 text-xs text-slate-400">Pay securely with PayPal. Debit or credit card appears only when PayPal makes it available.</p><fieldset disabled={disabled||!ready} className="mt-4 space-y-3 disabled:opacity-50"><div ref={paypalRef}/><div ref={cardRef}/></fieldset>{message&&<p className="mt-3 text-sm font-semibold text-slate-300">{message}</p>}</div>;
}