"use client";
import { useEffect, useRef, useState } from "react";

declare global { interface Window { paypal?: any } }
type Props={ disabled:boolean; successPath?:string; createOrderEndpoint?:string; captureOrderEndpoint?:string; details:{robloxUsername:string;robloxUserId:number|null;contactInfo:string;notes:string;items:{id:number;quantity:number}[];couponCode?:string;fulfillmentFlow?:"steal-an-egg"}; };
export default function PaypalCheckout({disabled,details,successPath="/payment-success",createOrderEndpoint="/api/paypal/create-order",captureOrderEndpoint="/api/paypal/capture-order"}:Props){
 const paypalRef=useRef<HTMLDivElement>(null),cardRef=useRef<HTMLDivElement>(null),detailsRef=useRef(details),disabledRef=useRef(disabled),failureRef=useRef(""); detailsRef.current=details; disabledRef.current=disabled; const [message,setMessage]=useState(""),[ready,setReady]=useState(false);
 useEffect(()=>{const clientId=process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID;if(!clientId){setMessage("PayPal sandbox is not configured yet.");return;}let dead=false;
 const render=()=>{if(dead||!window.paypal)return;if(paypalRef.current) paypalRef.current.replaceChildren();if(cardRef.current) cardRef.current.replaceChildren();const make=(el:React.RefObject<HTMLDivElement|null>)=>{const button=window.paypal.Buttons({style:{layout:"vertical",shape:"rect",color:"gold",label:"paypal"},onClick:(_:any,actions:any)=>{if(disabledRef.current){setMessage("Complete your delivery details and accept the policies first.");return actions.reject();}return actions.resolve();},createOrder:async()=>{setMessage("Creating secure payment...");const r=await fetch(createOrderEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(detailsRef.current)});const d=await r.json();if(!r.ok){failureRef.current=d.error||"Creating secure payment failed.";setMessage(failureRef.current);throw new Error(failureRef.current);}setMessage("");return d.orderID;},onApprove:async(data:any)=>{setMessage("Payment processing...");const r=await fetch(captureOrderEndpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderID:data.orderID})});const d=await r.json();if(!r.ok){setMessage(d.error||"Payment could not be completed. Please try again.");return;}setMessage("Payment completed successfully.");window.location.assign(successPath+"?orderId="+encodeURIComponent(d.bloxhopOrderId));},onCancel:()=>setMessage("Payment was cancelled. You can try again."),onError:()=>setMessage(failureRef.current||"Payment could not be completed. Please try again.")});if(!button.isEligible()){setMessage("PayPal is not available for this browser right now.");return;} if(el.current){Promise.resolve(button.render(el.current)).catch(()=>setMessage("PayPal buttons could not load. Disable any ad blocker and reload."));}};try{make(paypalRef);setReady(true);}catch(error){setMessage("PayPal buttons could not load: "+(error instanceof Error ? error.message : "unknown PayPal SDK error"));}};
 if(window.paypal){render();return()=>{dead=true;};}const script=document.createElement("script");script.src="https://www.paypal.com/sdk/js?client-id="+encodeURIComponent(clientId)+"&currency=USD&intent=capture&components=buttons,funding-eligibility";script.async=true;script.onload=render;script.onerror=()=>setMessage("PayPal could not load. Disable any ad blocker and reload.");document.body.appendChild(script);return()=>{dead=true;};},[successPath,createOrderEndpoint,captureOrderEndpoint]);
 return <div className="mt-5 rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><h3 className="text-base font-black text-slate-900">Payment Method</h3><p className="mt-1 text-xs text-slate-600">Pay securely with PayPal. Debit or credit card appears only when PayPal makes it available.</p><div className="mt-4 space-y-3"><div ref={paypalRef}/></div>{message&&<p className="mt-3 text-sm font-semibold text-slate-700">{message}</p>}</div>;
}