import LegalPageShell from "@/components/legal-page-shell";

export const metadata = {
  title: "Terms of Service | Bloxhop",
  description: "Terms that apply when using Bloxhop and placing orders.",
};

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service">
      <div className="space-y-5 text-slate-200 leading-7">
        <p className="text-sm text-sky-200/80">Effective Date: April 24, 2026</p>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">1. About Bloxhop</h2><p>Bloxhop Online Store is an independent online business based in the Philippines that provides digital gaming-related products and services. Bloxhop is not affiliated with, endorsed by, sponsored by, or officially connected with Roblox Corporation, Blox Fruits, Gamer Robot Inc., or other game developers or publishers unless expressly stated. Third-party trademarks, game names, logos, and related intellectual property belong to their respective owners.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">2. Products and Services</h2><p>Product descriptions, prices, availability, delivery methods, and customer requirements are shown on the relevant product pages. Unless a product page specifically states otherwise, products and services are fulfilled digitally rather than shipped physically.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">3. Orders</h2><p>Orders are accepted for fulfillment after successful payment confirmation and any applicable transaction or security review. Bloxhop may reject, cancel, delay, or suspend a transaction where there is reasonable suspicion of fraud, unauthorized payment, incorrect information, prohibited activity, product unavailability, or a violation of these Terms.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">4. Customer Information</h2><p>Customers must provide accurate information needed to process and deliver an order, including the correct gaming username or identifier where required. Bloxhop does not normally require customers to provide their passwords for order fulfillment.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">5. KYC AND TRANSACTION VERIFICATION</h2><p>Bloxhop may conduct reasonable identity, transaction, and risk verification when necessary for fraud prevention, payment-provider requirements, applicable legal requirements, or suspicious, unusual, disputed, unauthorized, or high-risk transactions.</p><p className="mt-2">Depending on the circumstances, Bloxhop may request a full name, email address, phone number, order information, payment or transaction reference, proof of payment, government-issued identification where reasonably necessary, or other information reasonably necessary for verification. Verification requests will be proportionate to the circumstances and may be required before an order is fulfilled or a refund is processed.</p><p className="mt-2">Bloxhop will never ask customers to provide passwords, private keys, authentication codes, or unrelated account credentials for transaction verification. If verification cannot be completed, Bloxhop may delay, reject, cancel, or refund a transaction where appropriate.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">6. Prohibited Transactions</h2><p>Bloxhop may not be used for fraudulent transactions, unauthorized or stolen payment methods, compromised accounts, account theft, money laundering, illegal goods or services, counterfeit goods, intellectual-property infringement, gambling or betting, or activities prohibited by applicable law or payment-provider rules.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">7. Pricing and Payment</h2><p>Prices are displayed in Philippine pesos unless otherwise stated. Payments are processed through available third-party payment providers, which may include Xendit when offered at checkout. Payment providers process payment information under their own terms, privacy policies, and security controls.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">8. Delivery</h2><p>Orders begin processing after successful payment confirmation. Delivery timing is an estimate and may vary. Please review the <a className="text-sky-300 hover:underline" href="/delivery">Delivery Policy</a> for fulfillment methods, timing factors, and customer requirements.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">9. Refunds</h2><p>Refund eligibility and the request process are described in the <a className="text-sky-300 hover:underline" href="/refund-policy">Refund Policy</a>. Nothing in these Terms limits rights that cannot legally be excluded under applicable consumer-protection law.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">10. Chargebacks and Disputes</h2><p>Customers should contact Bloxhop first regarding a legitimate transaction or delivery problem. Bloxhop may provide relevant transaction, delivery, verification, and communication records to payment providers when necessary to investigate a dispute or chargeback.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">11. Intellectual Property</h2><p>Bloxhop respects intellectual-property rights and does not intentionally offer products that infringe third-party rights. If a complaint arises, Bloxhop may investigate and remove, suspend, or discontinue the relevant listing.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">12. Suspension and Cancellation</h2><p>Bloxhop may suspend or cancel transactions when reasonably necessary for fraud prevention, security, legal or payment-provider compliance, investigation of suspicious activity, or prevention of prohibited transactions.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">13. Applicable Law and Updates</h2><p>These Terms are governed by applicable Philippine law. Bloxhop may update them to reflect operational, legal, or compliance changes; the current version will be posted on this page.</p></section>
        <section><h2 className="mb-2 text-xl font-semibold text-sky-200">14. Contact</h2><p><a className="text-sky-300 hover:underline" href="mailto:support@bloxhop.site">support@bloxhop.site</a><br />+63 945 339 2304<br />Bloxhop Online Store<br />Cebu City, Cebu, Philippines</p></section>
      </div>
    </LegalPageShell>
  );
}
