import {NextResponse} from "next/server";
import {adminSupabase} from "@/lib/supabase-admin";
import {requireAdmin} from "@/lib/admin-auth";
import {sendEmail} from "@/lib/email";
import {type AnnouncementContent,renderAnnouncementEmail,replaceProductToken} from "@/lib/announcement-email";
export const runtime="nodejs";export const maxDuration=60;
const RE=/^[^\s@]+@[^\s@]+\.[^\s@]+$/,SIZE=20,CONCURRENCY=2;
const F="id,subject,title,product_name,image_url,message,secondary_text,cta_text,cta_url,recipient_count,processed_count,successful_count,failed_count,current_batch,total_batches,retry_attempts,status,created_at,started_at,completed_at,sent_at,updated_at";
type Row={payer_email:string|null;contact_info:string|null;status:string|null;payment_status:string|null;delivery_status:string|null};
type Claimed={id:number;email:string;masked_email:string;batch_number:number};
const str=(v:unknown,n:number)=>typeof v==="string"?v.trim().slice(0,n):"";
const mail=(v:unknown)=>str(v,320).toLowerCase();
const err=(e:unknown)=>(e instanceof Error?e.message:"Email provider rejected the request.").replace(/[\r\n]+/g," ").slice(0,180);
function mask(v:string){const [n,d]=v.split("@");return `${n.slice(0,2)}***@${d}`}
function url(v:string){try{return ["http:","https:"].includes(new URL(v).protocol)}catch{return false}}
function announcement(v:unknown):(AnnouncementContent&{subject:string})|null{if(!v||typeof v!=="object")return null;const x=v as Record<string,unknown>,p=str(x.productName,120),a={subject:str(x.subject,180),productName:p,title:str(x.title,180),imageUrl:str(x.imageUrl,1500),message:str(x.message,5000),secondaryText:str(x.secondaryText,1000),ctaText:str(x.ctaText,60),ctaUrl:str(x.ctaUrl,1500)};if(!a.subject||!p||!a.title||!a.imageUrl||!a.message||!a.ctaText||!a.ctaUrl||!url(a.imageUrl)||!url(a.ctaUrl))return null;a.subject=replaceProductToken(a.subject,p);return a}
function eligible(r:Row){return [r.status,r.payment_status,r.delivery_status].some(v=>["pending","paid","free","complete","delivered"].some(x=>(v||"").toLowerCase().includes(x)))}
async function load(){const rows:Row[]=[];for(let from=0;;from+=1000){const {data,error}=await adminSupabase.from("orders").select("payer_email,contact_info,status,payment_status,delivery_status").range(from,from+999);if(error)throw Error("Could not load customer recipients.");rows.push(...((data||[]) as Row[]));if(!data||data.length<1000)break}const ok=rows.filter(eligible),set=new Set<string>();let records=0,skipped=0;for(const r of ok){const e=mail(r.payer_email||r.contact_info);if(!RE.test(e)){skipped++;continue}records++;set.add(e)}const list=[...set].sort();return{list,stats:{totalEligibleOrders:ok.length,uniqueValidEmails:list.length,duplicatesRemoved:Math.max(0,records-list.length),invalidOrEmptySkipped:skipped}}}
async function one(id:string){return(await adminSupabase.from("announcement_campaigns").select(F).eq("id",id).maybeSingle()).data}
async function snap(id?:string){let q=adminSupabase.from("announcement_campaigns").select(F).order("created_at",{ascending:false}).limit(1);if(id)q=q.eq("id",id);const c=(await q).data?.[0]||null;const activity=c?(await adminSupabase.from("announcement_campaign_activity").select("id,event_type,message,detail,masked_email,created_at").eq("campaign_id",c.id).order("created_at",{ascending:false}).limit(40)).data||[]:[];return{campaign:c,activity}}
async function send(items:Claimed[],subject:string,html:string){let i=0;async function work(){while(i<items.length){const item=items[i++];let success=true,reason:null|string=null;try{await sendEmail({to:item.email,subject,html})}catch(e){success=false;reason=err(e)}const {error}=await adminSupabase.rpc("record_announcement_result",{p_recipient_id:item.id,p_success:success,p_error:reason});if(error)throw Error("Could not save recipient progress.")}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,items.length)},work))}
export async function GET(){if(!await requireAdmin())return NextResponse.json({error:"Unauthorized"},{status:401});try{const [{stats},history,current]=await Promise.all([load(),adminSupabase.from("announcement_campaigns").select(F).order("created_at",{ascending:false}).limit(20),snap()]);return NextResponse.json({stats,history:history.error?[]:history.data||[],historyAvailable:!history.error,currentCampaign:current.campaign,activity:current.activity})}catch(e){console.error(err(e));return NextResponse.json({error:"Could not load announcement data."},{status:500})}}
export async function POST(request:Request){const admin=await requireAdmin();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await request.json() as Record<string,unknown>,action=body.action;
if(action==="test"){const a=announcement(body.announcement),to=mail(body.testEmail);if(!a)return NextResponse.json({error:"Complete all required announcement fields."},{status:400});if(!RE.test(to))return NextResponse.json({error:"Enter a valid test email address."},{status:400});await sendEmail({to,subject:a.subject,html:renderAnnouncementEmail(a,process.env.EMAIL_ASSET_BASE_URL||"https://bloxhop.site")});return NextResponse.json({success:true})}
if(action==="start"){const a=announcement(body.announcement),key=str(body.idempotencyKey,100);if(!a||!key)return NextResponse.json({error:"Complete all fields and confirm the campaign."},{status:400});const {list}=await load();if(!list.length)return NextResponse.json({error:"No valid customer recipients were found."},{status:400});const {data:c,error}=await adminSupabase.from("announcement_campaigns").insert({subject:a.subject,title:a.title,product_name:a.productName,image_url:a.imageUrl,message:a.message,secondary_text:a.secondaryText||null,cta_text:a.ctaText,cta_url:a.ctaUrl,recipient_count:list.length,total_batches:Math.ceil(list.length/SIZE),status:"preparing",created_by:admin.id,idempotency_key:key}).select("id").single();if(error||!c)return NextResponse.json({error:error?.code==="23505"?"Another campaign is active or this request was already submitted.":"Run the updated announcement SQL migration first."},{status:error?.code==="23505"?409:503});for(let s=0;s<list.length;s+=500){const {error:e}=await adminSupabase.from("announcement_campaign_recipients").insert(list.slice(s,s+500).map(email=>({campaign_id:c.id,email,masked_email:mask(email),status:"queued"})));if(e){await adminSupabase.from("announcement_campaigns").delete().eq("id",c.id);throw Error("Could not prepare campaign recipients.")}}await adminSupabase.from("announcement_campaigns").update({status:"queued"}).eq("id",c.id);await adminSupabase.from("announcement_campaign_activity").insert({campaign_id:c.id,event_type:"queued",message:"Campaign queued",detail:`${list.length} unique recipients prepared`});return NextResponse.json({success:true,...await snap(c.id)})}
const id=str(body.campaignId,100);if(!id)return NextResponse.json({error:"Missing campaign."},{status:400});
if(action==="retry"){const c=await one(id);if(!c||c.status!=="completed_with_errors"||c.failed_count<1)return NextResponse.json({error:"No failed recipients are available to retry."},{status:409});const {error:e}=await adminSupabase.from("announcement_campaign_recipients").update({status:"queued",safe_error:null,processed_at:null}).eq("campaign_id",id).eq("status","failed");if(e)throw Error("Could not queue failed recipients.");const {data:u,error:x}=await adminSupabase.from("announcement_campaigns").update({status:"queued",processed_count:c.successful_count,failed_count:0,current_batch:0,total_batches:Math.ceil(c.failed_count/SIZE),completed_at:null,sent_at:null,retry_attempts:c.retry_attempts+1}).eq("id",id).eq("status","completed_with_errors").select("id").maybeSingle();if(x||!u)return NextResponse.json({error:"Retry was already started."},{status:409});await adminSupabase.from("announcement_campaign_activity").insert({campaign_id:id,event_type:"retry",message:"Retry queued",detail:`${c.failed_count} failed recipients will be retried`});return NextResponse.json({success:true,...await snap(id)})}
if(action!=="process")return NextResponse.json({error:"Invalid action."},{status:400});const c=await one(id);if(!c)return NextResponse.json({error:"Campaign not found."},{status:404});if(!["preparing","queued","sending"].includes(c.status))return NextResponse.json({success:true,...await snap(id)});const {data,error}=await adminSupabase.rpc("claim_announcement_batch",{p_campaign_id:id,p_batch_size:SIZE});if(error)throw Error("Could not claim the next batch.");const items=(data||[]) as Claimed[];if(items.length){const content:AnnouncementContent={subject:c.subject,productName:c.product_name,title:c.title,imageUrl:c.image_url,message:c.message,secondaryText:c.secondary_text||"",ctaText:c.cta_text,ctaUrl:c.cta_url};await send(items,c.subject,renderAnnouncementEmail(content,process.env.EMAIL_ASSET_BASE_URL||"https://bloxhop.site"));await adminSupabase.from("announcement_campaign_activity").insert({campaign_id:id,event_type:"batch",message:`Batch ${items[0].batch_number} processed`,detail:`${items.length} provider requests completed`})}const {error:f}=await adminSupabase.rpc("finish_announcement_campaign",{p_campaign_id:id});if(f)throw Error("Could not finalize campaign.");return NextResponse.json({success:true,...await snap(id)})}catch(e){console.error(err(e));return NextResponse.json({error:err(e)},{status:500})}}
