"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
type State={loading:boolean;paid:boolean;orderId:string|null};
export default function PaymentSuccessPage(){
 const search=useSearchParams();const [state,setState]=useState<State>({loading:true,paid:false,orderId:null});
 useEffect(()=>{const orderId=search.get("orderId");if(!orderId){setState({loading:false,paid:false,orderId:null});return;}fetch("/api/paypal/order-status?orderId="+encodeURIComponent(orderId),{cache:"no-store"}).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>setState({loading:false,paid:ok&&data.paid===true,orderId:ok?String(data.orderId):null})).catch(()=>setState({loading:false,paid:false,orderId:null}));},[search]);
 const title=state.loading?"Confirming payment…":state.paid?"Payment confirmed":"Payment status unavailable";
 const text=state.loading?"Checking your secure PayPal payment.":state.paid?"Your payment was securely verified and your order is now in the fulfillment queue.": "We could not confirm this payment in this browser. Please use Track Order or contact support.";
 return <main className="min-h-screen bg-[#070b14] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_top_left,rgba(59,130,246,0.12),transparent_30%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,0.08),transparent_30%)]"/><section className="relative mx-auto flex max-w-3xl px-6 py-20"><div className="w-full rounded-[2rem] border border-emerald-400/20 bg-[#0b1220]/90 p-8 text-center shadow-[0_25px_80px_rgba(0,0,0,0.45)] md:p-12"><div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full border border-emerald-400/20 bg-emerald-400/10 text-4xl">{state.paid?"✓":"…"}</div><p className="mt-6 text-sm font-bold uppercase tracking-[0.25em] text-emerald-300">Bloxhop payment</p><h1 className="mt-4 text-4xl font-black md:text-5xl">{title}</h1><p className="mt-5 text-base leading-7 text-slate-300">{text}</p>{state.paid&&state.orderId&&<p className="mt-6 text-sm font-bold text-emerald-200">Order #{state.orderId}</p>}<div className="mt-10 flex flex-wrap justify-center gap-4"><Link href="/track-order" className="rounded-2xl bg-blue-500 px-8 py-4 font-bold text-white">Track Order</Link><Link href="/home" className="rounded-2xl border border-white/10 bg-white/5 px-8 py-4 font-bold text-white">Back to Store</Link></div></div></section></main>;
}