"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Order = { id: number; items: Array<{ name?: string; quantity?: number; price?: number }> | null; total_price: number; payment_status: string | null; status: string | null; payment_method: string | null; xendit_reference_id?: string | null; roblox_username: string | null; contact_info: string | null; notes: string | null; created_at: string };
export default function AccountOrderDetail({ params }: { params: Promise<{ id: string }> }) {
  const [order, setOrder] = useState<Order | null>(null); const [notFound, setNotFound] = useState(false);
  useEffect(() => { params.then(async ({ id }) => { const response = await fetch(`/api/account/orders/${id}`, { cache: "no-store" }); if (!response.ok) { setNotFound(true); return; } const result = await response.json(); setOrder(result.order); }); }, [params]);
  if (notFound) return <main className="min-h-[calc(100vh-82px)] bg-[#06101d] px-4 py-16 text-center text-white"><h1 className="text-2xl font-black">Order not found</h1><Link href="/account/orders" className="mt-5 inline-block font-bold text-blue-300">Back to My Orders</Link></main>;
  if (!order) return <main className="min-h-[calc(100vh-82px)] bg-[#06101d] px-4 py-16 text-center text-slate-300">Loading your order…</main>;
  return <main className="min-h-[calc(100vh-82px)] bg-[#06101d] px-4 py-10 text-white sm:px-6 sm:py-14"><div className="mx-auto max-w-3xl"><Link href="/account/orders" className="text-sm font-bold text-blue-300 hover:text-white">← My Orders</Link><div className="mt-5 rounded-[1.75rem] border border-blue-300/15 bg-[#0b1728] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.24em] text-blue-300">Order #{order.payment_method === "Shopify" && order.xendit_reference_id ? order.xendit_reference_id : order.id}</p><div className="mt-3 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-black">Order Details</h1><p className="mt-2 text-sm text-slate-300">Placed {new Date(order.created_at).toLocaleString()}</p></div><p className="text-2xl font-black text-emerald-300">${Number(order.total_price || 0).toFixed(2)}</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2"><Info label="Payment" value={order.payment_status || "Pending"} /><Info label="Fulfillment" value={order.status || "Pending"} /><Info label="Method" value={order.payment_method || "—"} /><Info label="Roblox username" value={order.roblox_username || "—"} /></div><div className="mt-7 border-t border-blue-300/15 pt-6"><h2 className="text-lg font-black">Items</h2><div className="mt-3 space-y-2">{(order.items || []).map((item, index) => <div key={index} className="flex justify-between rounded-xl bg-[#07111f] px-4 py-3 text-sm"><span>{item.name || "Digital item"}{item.quantity && item.quantity > 1 ? ` × ${item.quantity}` : ""}</span><span>${Number(item.price || 0).toFixed(2)}</span></div>)}</div></div></div></div></main>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-blue-300/15 bg-[#07111f] p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }